config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :rider_users, ActiveAdmin::Devise.config.merge({path: '/rider'})
  ActiveAdmin.routes(self)
  devise_for :users
  resources :dashboard, only: [:index]
  resources :restaurants, only: [ :index, :show]
  root to: 'pages#home'
  get 'error', to: 'pages#error'
  get 'faqs', to: 'pages#faqs'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create] 
  resources :menu_items, only: [ :show ] do
    resources :order_items, only: [ :create ]
  end
  resources :order_items, only: [ :destroy]
  resources :orders, only: [:index, :create, :destroy] do
    resources :payments, only: :new
    member do
      get 'status'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  require "sidekiq/web"
  authenticate :admin_user do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end
end

app/views/partials/_cart_minimum_warning.html.erb
<%if @cart.order_items.present? && @cart.restaurant.min_spend.present? && @cart.is_below_minimum_spend%>
    <p class="modal__cart--alert">Your order is below the £<%=to_pounds(@cart.restaurant.min_spend)%> minimum for this restaurant. Add more items to continue with your order.</p>
<%end%>

app/views/partials/_footer.html.erb
<div class="footer">
    <div class="container">
        <div class="row footer__border">
            <div class="col-12 col-lg-4 footer__column">
                <div class="footer__column--box">
                    <div class="footer__column--box">
                        <%= link_to "Restaurants Admin", admin_dashboard_path %>
                        <%= link_to "Rider Portal", rider_dashboard_path %>
                        <div class="links">
                            <a href="https://www.instagram.com/veganwheels_glasgow/" target="_blank"><i class="fab fa-instagram"></i></a> 
                            <a href="https://business.facebook.com/VeganWheelie/" target="_blank"><i class="fab fa-facebook-square"></i></a> 
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-4 footer__column">
                <div class="footer__column--box">
                    <%= link_to "FAQs", faqs_path %>
                    <%= link_to "Terms and Conditions", terms_path %>
                    <%= link_to "Privacy Policy", privacy_path %>
                    <%= link_to "Illustrations", "https://absurd.design/", target: "_blank" %>
                </div>
            </div>
            <div class="col-12 col-lg-4 footer__column">
                <div class="footer__column--box">
                    <p class="title">Contact us</p>
                    <div class="email">
                        <i class="fas fa-envelope"></i>
                        <p><%= Business.first.email %></p>
                    </div>
                    <div class="phone">
                        <i class="fas fa-phone-square-alt"></i>
                        <p><%= Business.first.phone %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/partials/_modal_cart.html.erb
<div class = "modal__box modal__cart">
    <div class="modal__cart--items">
        <div class="modal__cart--top">
            <h3 class="font-weight-bold">Your order from <%=@cart.restaurant.name%></h3>
        </div>
        <%unique_cart = get_unique(@cart)%>
        <%unique_cart.each do |order_item|%>
        <div id="item-<%= order_item.id %>">
            <div class="modal__cart--item item-js" >
                <%duplicates = get_duplicates(order_item, @cart)%>
                <%if duplicates.empty?%>
                    <div class="modal__cart--itemwrapper">
                        <%= link_to order_item_path(order_item),
                            method: :delete,
                            remote: true do %>
                            <i class="fas fa-times"></i>
                        <%end%>
                        <div class="item">   
                            <p><%=order_item.quantity%> <%=order_item.menu_item.name%></p>
                        </div>
                    </div>
                    <p>£<%=to_pounds(order_item.total_price)%></p>
                <%else%>
                    <div class="modal__cart--itemwrapper">
                        <%all_items = duplicates.clone%>
                        <%all_items << order_item%>
                        <%= link_to order_item_path(all_items),
                            method: :delete,
                            remote: true do %>
                            <i class="fas fa-times"></i>
                        <%end%>
                        <div class="item">
                            <%quantity_sum = order_item.quantity + duplicates.each_with_object([]) {|oi,array| array<<oi.quantity }.sum%>
                            <%price_sum = order_item.total_price + duplicates.each_with_object([]) {|oi,array| array<<oi.total_price }.sum%>
                            <p><%=quantity_sum%> <%=order_item.menu_item.name%></p>
                        </div>
                    </div>
                    <p>£<%=to_pounds(price_sum)%></p>
                <%end%>
            </div>
            <%if order_item.order_item_options.present?%>
                <%order_item.order_item_options.each do |option|%>
                <div class="modal__cart--item">
                    <p class="modal__cart--side"><%=option.menu_option.name%></p>
                    <%if duplicates.empty?%>
                        <%if option.unit_price != 0%>
                            <p>£<%=to_pounds(option.total_price)%></p>
                        <%end%>
                    <%else%>
                        <%if option.unit_price != 0%>
                            <%count = duplicates.count + 1%>
                            <%total = count*option.unit_price%>
                            <p>£<%=to_pounds(total)%></p>
                        <%end%>
                    <%end%>

                </div>
                <%end%>
            <%end%>
            <%if order_item.note.present?%>
                <div class="modal__cart--item">
                    <div class="modal__cart--side">
                        <p>Note: <%=order_item.note%></p>
                    </div>
                </div>
            <%end%>
            </div>
        <%end%>
        <div class="modal__cart--item">
            <p class="font-weight-bold">Subtotal</p>
            <p id="subtotal">£<%=to_pounds(@cart.get_subtotal)%></p>
        </div>
        <div class="modal__cart--item">
            <p>Delivery charge</p>
            <p>£<%=to_pounds(Business.first.delivery_price)%></p>
        </div>
        <div class="modal__cart--line"></div>
        <div class="modal__cart--item">
            <p class="font-weight-bold uppercase">Total</p>
            <p id="total">£<%= to_pounds(@cart.get_total)%></p>
        </div>
        <div id="modal__cart--warning">
            <%= render 'partials/cart_minimum_warning', cart: @cart%>
        </div>
        <div class="modal__cart--form">
            <div id="modal-cart-form">
                <%= render 'partials/modal_cart_form', cart: @cart%>
            </div>
            <div class="button__fill button__fill--redl" id="cart-modal-close">Continue browsing</div>
        </div>
    </div>
</div>

app/views/partials/_modal_cart_bg.html.erb
<div class="modal-item modal__bckg">
</div>
<div class="modal-cart modal__bckg">
        <%if !session[:cart_id].nil? && Cart.find(session[:cart_id]).order_items.present?%>
        <%@cart = Cart.find(session[:cart_id])%>
            <%= render 'partials/modal_cart', cart: @cart%>
        <%end%>
</div> 

app/views/partials/_modal_cart_form.html.erb
<%if @cart.order_items.present?%>
    <%= form_with(model: Order.new, local: true) do |form| %>
            <%= form.label :delivery_instructions, 'Delivery Instructions' %>
            <div><%= form.text_area :delivery_instructions %></div>
            <%= form.hidden_field :cart_id, value: @cart.id %>
            <%= form.submit 'Check out', class: 'button__fill button__fill--red',disabled: @cart.is_below_minimum_spend %>
    <% end %>
<%end%>

app/views/partials/_modal_item.html.erb
<div class="modal__box modal__item <%= item.id %>"> 
    <div class="modal__item--text">
        <div class="modal__item--top">
            <h3><%= item.name %></h3>
            <h3 class="price">£
            <%= to_pounds(item.price) %>
            </h3>
        </div>
        <% if item.description.present? %>
            <div class="modal__item--description">
                <p><%= item.description %></p>
            </div>
        <% end %>
        <form class="order-form" id="order-form" accept-charset="UTF-8" data-remote="true" method="post">
        
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div>
                <label class="font-weight-bold" for="order_item_options">Options</label>

                <% if item.menu_options.single_select.any? %>
                    <div>
                    <select name="order_item[order_item_options_attributes][-1][menu_option_id]" id="order_item_options" form="order-form">
                        <% item.menu_options.single_select.each_with_index do |option, index| %>
                            <option value="<%= option.id %>">
                                <%= option.name %> 
                                <% if option.price != nil %> 
                                 £<%= to_pounds(option.price) %>
                                <% end %>
                            </option>
                        <% end %>
                    </select>
                    </div>
                <% end %>
                
                <% if item.menu_options.multiple_select.any? %>
                    <% item.menu_options.multiple_select.each_with_index do |option, index| %>
                            <div>
                                <input type="checkbox" name="order_item[order_item_options_attributes][<%= index %>][menu_option_id]" id="order_item_options" value="<%= option.id %>"> 
                                    <%= option.name %> 
                                    <% if option.price != nil %> 
                                        £<%= to_pounds(option.price) %>
                                    <% end %>
                                
                                <% if option.description.present? %>
                                    <p class="option__box"><%= option.description %></p>
                                <% end %>
                            </div>
                    <% end %>
                <% end %>
            </div>

            <div>
                <label class="font-weight-bold" for="order_item_note">Special requests</label>
                <div>
                    <textarea name="order_item[note]" id="order_item_note"></textarea>
                </div>
            </div>

            <div class="modal__item--bottom">
                <div class="quantity-select">
                    <div class="button--quantity" id="subtract"><i class="fas fa-minus"></i></div>
                    <input type="text" name="order_item[quantity]" id="order_item_quantity" value="1">
                    <div class="button--quantity" id="add"><i class="fas fa-plus"></i></div>
                </div>
            </div>

            <button type="submit" class="button__fill button__fill--green">Add to order</button>
            <div class="button__fill button__fill--greenl" id="modal-close">Cancel</div>
        </form>
    </div>
</div>                       

app/views/partials/_modal_warning.html.erb
<div class = "modal__box modal__cart">
    <%if @order.restaurant.is_currently_closed?%>
        <p>Sorry, this restaurant is now closed.</p>
    <%elsif @order.user.is_outside_delivery_area(@order.restaurant)%>
        <p>Sorry, you are outside the delivery area for this restaurant. Change your address in the dashboard to proceed.</p>
    <%end%>

    <div class="btn btn-success mt-5">OK</div>
</div>

app/views/partials/_nav.html.erb
<div class="navigation">
    <div class="container navigation__main">
        <div class="navigation__toggle"">
            <i class="fas fa-bars"></i>
        </div>
        <div class="navigation__logo">
            <%= link_to "Veganwheels", root_path %>
        </div>
        <% if user_signed_in? %>           
            <div id="user_icon_1" class="user_icon user_icon--mobile">
                <i class="fas fa-user"></i>
                <%= render "partials/user_menu" %>
            </div> 
        <% end %>
        <div id="nav_section_1">
            <% if !session[:cart_id].nil? && Cart.find(session[:cart_id]).order_items.present? %>
                <% @cart = Cart.find(session[:cart_id]) %>
                <div class="nav_cart nav_cart--tablet">
                    <div class="nav_cart--price">
                        <i class="fas fa-shopping-basket"></i>
                        <p>£<%= to_pounds(@cart.get_total) %></p>
                    </div>
                    <div>|</div>
                    <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
                </div>
            <% elsif user_signed_in? && current_user.orders.where(state: "pending").present? %>
                <% @cart = current_user.orders.where(state: "pending").first.cart %>

                <%= link_to new_order_payment_path(current_user.orders.where(state: "pending").first) do %>
                    <div class="nav_cart nav_cart--tablet">
                        <div class="nav_cart--price">
                            <i class="fas fa-shopping-basket"></i>
                            <p>£<%= to_pounds(@cart.get_total) %></p>
                        </div>
                        <div>|</div>
                        <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
                    </div>
                <% end %>
            <% end %>      
        </div>
        <div class="navigation__links">
            <div class="navigation__links--1 padding-small">
                <div class="link-blob"></div>
                <%= link_to "See all restaurants", restaurants_path %>
            </div>
            <div class="navigation__links--2 padding-small">
                <div class="link-blob"></div>
                <%= link_to "About us", root_path(anchor: "about-section") %>
            </div>
            <div class="navigation__links--3 padding-small">
                <div class="link-blob"></div>
                <%= link_to "Join us", new_contact_path %>
            </div>
       
            <div id="nav_section_2">
                <% if !session[:cart_id].nil? && Cart.find(session[:cart_id]).order_items.present? %>
                <% @cart = Cart.find(session[:cart_id]) %>
                    <div class="nav_cart nav_cart--normal">
                        <div class="nav_cart--price">
                            <i class="fas fa-shopping-basket"></i>
                            <p>£<%= to_pounds(@cart.get_total) %></p>
                        </div>
                        <div>|</div>
                        <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
                    </div>
                <% elsif user_signed_in? && current_user.orders.where(state: "pending").present? %>
                    <% @cart = current_user.orders.where(state: "pending").first.cart %>

                    <%= link_to new_order_payment_path(current_user.orders.where(state: "pending").first) do %>
                        <div class="nav_cart nav_cart--normal">
                            <div class="nav_cart--price">
                                <i class="fas fa-shopping-basket"></i>
                                <p>£<%= to_pounds(@cart.get_total) %></p>
                            </div>
                            <div>|</div>
                            <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
                        </div>
                    <% end %>
                <% end %>      
            </div>
        
            <% if user_signed_in? %>           
                <div id="user_icon_2" class="user_icon user_icon--normal">
                    <i class="fas fa-user"></i>
                    <%= render "partials/user_menu" %>
                </div>  
            <% else %>
                <div class="navigation__links--4 padding-small" id="">
                    <%= link_to "Log in", new_user_session_path, id: "sign_up" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<div id="nav_section_3">
    <% if !session[:cart_id].nil? && Cart.find(session[:cart_id]).order_items.present? %>
    <% @cart = Cart.find(session[:cart_id]) %>
        <div class="nav_cart nav_cart--mobile">
            <div class="nav_cart--price">
                <i class="fas fa-shopping-basket"></i>
                <p>£<%= to_pounds(@cart.get_total) %></p>
            </div>
            <div>|</div>
            <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
        </div>
    <% elsif user_signed_in? && current_user.orders.where(state: "pending").present? %>
        <% @cart = current_user.orders.where(state: "pending").first.cart %>

        <%= link_to new_order_payment_path(current_user.orders.where(state: "pending").first) do %>
            <div class="nav_cart nav_cart--mobile">
                <div class="nav_cart--price">
                    <i class="fas fa-shopping-basket"></i>
                    <p>£<%= to_pounds(@cart.get_total) %></p>
                </div>
                <div>|</div>
                <p class="uppercase"><%= pluralize(@cart.get_quantity, "item") %></p>
            </div>
        <% end %>
    <% end %>      
</div>

app/views/partials/_nav_cart_full.html.erb
<div id="nav_cart--full" style="display:none;">
<div class="nav_cart--arrow"></div>
    <div class="nav_cart--items">
        <%unique_cart = get_unique(@cart)%>
        <%unique_cart.each do |order_item|%>
            <div class="nav_cart--item item-js" id="item-<%= order_item.id %>">
                <%duplicates = get_duplicates(order_item, @cart)%>
                <%if duplicates.empty?%>
                    <div class="nav_cart--itemwrapper">
                        <%= link_to order_item_path(order_item),
                            method: :delete,
                            remote: true do %>
                            <i class="far fa-trash-alt"></i>
                        <%end%>
                        <div class="item">   
                            <p><%=order_item.quantity%> <%=order_item.menu_item.name%></p>
                        </div>
                    </div>
                    <p>£<%=to_pounds(order_item.total_price)%></p>
                <%else%>
                    <div class="nav_cart--itemwrapper">
                        <%all_items = duplicates.clone%>
                        <%all_items << order_item%>
                        <%= link_to order_item_path(all_items),
                            method: :delete,
                            remote: true do %>
                            <i class="far fa-trash-alt"></i>
                        <%end%>
                        <div class="item">
                            <%quantity_sum = order_item.quantity + duplicates.each_with_object([]) {|oi,array| array<<oi.quantity }.sum%>
                            <%price_sum = order_item.total_price + duplicates.each_with_object([]) {|oi,array| array<<oi.total_price }.sum%>
                            <p><%=quantity_sum%> <%=order_item.menu_item.name%></p>
                        </div>
                    </div>
                    <p>£<%=to_pounds(price_sum)%></p>
                <%end%>
            </div>
            <%if order_item.order_item_options.present?%>
                <%order_item.order_item_options.each do |option|%>
                    <p class="nav_cart--side"><%=option.menu_option.name%></p>
                <%end%>
            <%end%>
        <%end%>
        <div class="nav_cart--item">
            <p class="font-weight-bold">Subtotal</p>
            <p>£<%=to_pounds(@cart.get_subtotal)%></p>
        </div>
        <div class="nav_cart--item">
            <p>Delivery charge</p>
            <p>£3.50</p>
        </div>
        <div class="nav_cart--line"></div>
        <div class="nav_cart--item">
            <p class="font-weight-bold uppercase">Total</p>
            <p>£<%= to_pounds(@cart.get_total)%></p>
        </div>
    </div>
</div>

app/views/partials/_order.html.erb
<div class="dashboard__box--info">
    <a data-toggle="collapse" href="#collapse-<%=order.id%>" aria-expanded="false" aria-controls="collapse-<%=order.id%>">
        <div class="dashboard__box--margin dashboard__box--order">
            <h4 class="uppercase font-weight-bold "><%=order.restaurant.name%></h4>
            <h4 class="uppercase font-weight-bold ">£ <%=to_pounds(order.total_price)%></h4>
        </div>
        <p class="dashboard__box--margin">Order <%=order.id%> placed at<%=order.order_time.strftime(" %l:%M %p")%> on <%=order.order_time.strftime("%e %B %Y")%></p>
        <p class="dashboard__box--margin dashboard__box--<%=order.status_report.keys.first.to_s%>"><%=order.status_report.values.first%></p>
        <div class="d-flex justify-content-center pt-2 pb-2">
            <i class="fas fa-angle-down"></i>
        </div>
    </a>
    <div class="collapse" id="collapse-<%=order.id%>">
        <%= render 'partials/order_details', order: order%>
    </div>
</div>

app/views/partials/_order_details.html.erb
<div class="dashboard__box--details">
    <%get_unique(order.cart).each do |order_item|%>
        <div class="dashboard__box--item">
            <%duplicates = get_duplicates(order_item, order.cart)%>
            <%if duplicates.empty?%>
                <div class="modal__cart--itemwrapper">
                    <div>   
                        <p class="font-weight-bold"><%=order_item.quantity%> <%=order_item.menu_item.name%></p>
                    </div>
                </div>
                <p>£<%=to_pounds(order_item.total_price)%></p>
            <%else%>
                <div class="modal__cart--itemwrapper">
                    <div>
                        <%quantity_sum = order_item.quantity + duplicates.each_with_object([]) {|oi,array| array<<oi.quantity }.sum%>
                        <%price_sum = order_item.total_price + duplicates.each_with_object([]) {|oi,array| array<<oi.total_price }.sum%>
                        <p class="font-weight-bold"><%=quantity_sum%> <%=order_item.menu_item.name%></p>
                    </div>
                </div>
                <p>£<%=to_pounds(price_sum)%></p>
            <%end%>
        </div>
        <%if order_item.order_item_options.present?%>
            <%order_item.order_item_options.each do |option|%>
            <div class="dashboard__box--item">
                <p class="modal__cart--side"><%=option.menu_option.name%></p>
                <%if duplicates.empty?%>
                    <%if option.unit_price != 0%>
                        <p>£<%=to_pounds(option.total_price)%></p>
                    <%end%>
                <%else%>
                    <%if option.unit_price != 0%>
                        <%count = duplicates.count + 1%>
                        <%total = count*option.unit_price%>
                        <p>£<%=to_pounds(total)%></p>
                    <%end%>
                <%end%>
            </div>
            <%end%>
        <%end%>
        <%if order_item.note.present?%>
            <div class="dashboard__box--item">
                <div class="modal__cart--side">
                    <p>Note: <%=order_item.note%></p>
                </div>
            </div>
        <%end%>
    <%end%>

    <div class="dashboard__box--item">
        <p class="font-weight-bold">Delivery charge</p>
        <p>£<%=to_pounds(order.delivery_price)%></p>
    </div>

    <%if order.is_assigned && !order.delivery.is_delivered%>
        <div>
            <p>Your rider is <%=order.delivery.rider_user.first_name.capitalize%>.</p>
            <p>You can contact them on <%=order.delivery.rider_user.phone%></p>
        </div>
    <%end%>
</div>

app/views/partials/_restaurants_index.html.erb
<%if @restaurants.present? %>
    <div class="cards">
        <% @restaurants.each do |restaurant| %>
            <%if restaurant.is_published%>
                <%= link_to restaurant_path(restaurant) do %>
                    <div class="card card--<%= restaurant.imagekey %>">
                        <div class="card__title">
                            <% restaurant.name.split.each do |word| %>
                            <h1><%=word%></h1>
                            <%end%>
                        </div>
                        <div class="card__mask card__mask--<%= restaurant.imagekey %>">
                            <%if restaurant.photo.attached?%>
                                <%= cl_image_tag restaurant.photo.key, crop: :fill %>
                            <%else%>
                                <%= image_tag "restaurant.jpg"%>
                            <%end%>
                        </div>
                    </div>
                <%end%>
            <%end%>
        <%end%> 
    </div>
<%else%>
    <div class="row justify-content-center">
        <h1 class="margin-large">
            Sorry, looks like we are not in your area yet!
        </h1>
    </div>
<%end%>

app/views/partials/_restaurants_index_filter.html.erb
<%= simple_form_for :search, 
    url: restaurants_path, 
    remote: true,
    html: {id: :form, class: "mx-auto"},
    method: "GET" do |f| %>
    <%= f.input :postcode, 
    input_html: {value: current_user.postcode },
    as: :hidden %>  
    <%= f.button :submit, 'See restaurants that deliver to you', class: 'button__fill button__fill--green button__filter', data: { disable_with: false } %> 
<% end %>

app/views/partials/_user_menu.html.erb
<div id="user_menu" class="speech__box" style="display:none;">
    <div class="speech__box--arrow"></div>
    <div class="speech__box--items">
        <div class="speech__box--item font-weight-bold pb-2">
            <%=current_user.name%>
            <%=puts current_user%>
        </div>
        <div class="speech__box--item speech__box--link">
            <%= link_to "Dashboard", dashboard_index_path%>
        </div>
        <div class="speech__box--item speech__box--link">
            <%= link_to "Log out", destroy_user_session_path, method: :delete%>
        </div>
    </div>
</div>