config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :rider_users, ActiveAdmin::Devise.config.merge({path: '/rider'})
  ActiveAdmin.routes(self)
  devise_for :users
  resources :dashboard, only: [:index]
  resources :restaurants, only: [ :index, :show]
  root to: 'pages#home'
  get 'error', to: 'pages#error'
  get 'faqs', to: 'pages#faqs'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create] 
  resources :menu_items, only: [ :show ] do
    resources :order_items, only: [ :create ]
  end
  resources :order_items, only: [ :destroy]
  resources :orders, only: [:index, :create, :destroy] do
    resources :payments, only: :new
    member do
      get 'status'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  require "sidekiq/web"
  authenticate :admin_user do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end
end

app/models/menu_option.rb
class MenuOption < ApplicationRecord
  belongs_to :menu_item
  has_one :restaurant, through: :menu_item
  has_many :order_item_options, dependent: :restrict_with_error
  has_many :order_items, through: :order_item_options
  validates :name, presence: true
  validates :description, length: { maximum: 50 }

  scope :single_select, -> { where(is_single: true) }
  scope :multiple_select, -> { where(is_single: false) }
end

app/helpers/menu_options_helper.rb
module MenuOptionsHelper
end

app/views/admin/menu_options/_form.html.erb
<% if current_admin_user.role == "admin" %>
  <%= render partial: "form_admin", resource: @menu_option %>
<% else %>
  <%= render partial: "form_restaurant", resource: @menu_option %>
<% end %>

app/views/admin/menu_options/_form_admin.html.erb
<%= semantic_form_for [:admin, @menu_option], builder: ActiveAdmin::FormBuilder do |f| %>
    <%= f.semantic_errors %>
    <%= f.inputs "Side" do %>
        <%= f.input :menu_item %>
        <%= f.input :name %>
        <%= f.input :price, :label => "Prince in pence" %>
        <%= f.input :is_single, :label => "Single selection only" %>
        <%= f.input :description, :label => "Description (max 50 characters)" %>
    <% end %>
    <%= f.actions do %>
      <%= f.action(:submit) %>
      <%= f.action(:cancel) %>
    <% end %>
<% end %>

app/views/admin/menu_options/_form_restaurant.html.erb
<%= semantic_form_for [:admin, @menu_option], builder: ActiveAdmin::FormBuilder do |f| %>
    <%= f.semantic_errors %>
    <%= f.inputs "Side" do %>
        <%= f.input :menu_item, :as => :select, :collection => MenuItem.where(restaurant_id: current_admin_user.restaurant) %>
        <%= f.input :name %>
        <%= f.input :price, :label => "Prince in pence" %>
        <%= f.input :is_single, :label => "Single selection only" %>
        <%= f.input :description, :label => "Description (max 50 characters)" %>
    <% end %>
    <%= f.actions do %>
      <%= f.action(:submit) %>
      <%= f.action(:cancel) %>
    <% end %>
<% end %>