config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :rider_users, ActiveAdmin::Devise.config.merge({path: '/rider'})
  ActiveAdmin.routes(self)
  devise_for :users
  resources :dashboard, only: [:index]
  resources :restaurants, only: [ :index, :show]
  root to: 'pages#home'
  get 'error', to: 'pages#error'
  get 'faqs', to: 'pages#faqs'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create] 
  resources :menu_items, only: [ :show ] do
    resources :order_items, only: [ :create ]
  end
  resources :order_items, only: [ :destroy]
  resources :orders, only: [:index, :create, :destroy] do
    resources :payments, only: :new
    member do
      get 'status'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  require "sidekiq/web"
  authenticate :admin_user do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one_attached :photo
  has_many :menu_items, dependent: :restrict_with_error
  has_many :sections, dependent: :restrict_with_error
  has_many :orders, dependent: :restrict_with_error
  belongs_to :admin_user
  validates :phone, telephone_number: { country: :GB, types: [:mobile, :fixed_line] }
  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :postcode, presence: true
  validate :can_be_published
  before_save :postcode_is_formatted
  geocoded_by :address
  after_validation :geocode

  def is_currently_closed?
    self.before_opening_time? || self.after_closing_time? || self.is_closed_today? || !self.is_open
  end

  def is_closed_today?
    open_today = Time.current.strftime("%A").downcase + "_opens_at"
    close_today = Time.current.strftime("%A").downcase + "_closes_at"
    opens_at_time = self.send open_today
    closes_at_time = self.send close_today
    return opens_at_time == closes_at_time || opens_at_time.nil?
  end

  def before_opening_time?
    if Time.current.dst?
      Time.current < self.opening_time_today - 1.hour
    else
      Time.current < self.opening_time_today
    end
  end

  def after_closing_time?
    if Time.current.dst?
      Time.current > self.closing_time_today - 1.hour
    else
      Time.current > self.closing_time_today
    end
  end

  def opening_time_today
    opening_today = Time.current.strftime("%A").downcase + "_opens_at"
    opening_time_Y2K = self.send opening_today
    opening_time_hour_min = opening_time_Y2K.strftime("%I:%M %p")
    Time.parse opening_time_hour_min
  end

  def closing_time_today
    closing_today = Time.current.strftime("%A").downcase + "_closes_at"
    closing_time_Y2K = self.send closing_today
    closing_time_hour_min = closing_time_Y2K.strftime("%I:%M %p")
    Time.parse closing_time_hour_min
  end

  def address
    address = [street_address, city, county, postcode, country].reject { |e| e.to_s.empty? }
    address.join(", ")
  end

  def opening_hours
    days = [[monday_opens_at, monday_closes_at, "Monday"], [tuesday_opens_at, tuesday_closes_at, "Tuesday"], [wednesday_opens_at, wednesday_closes_at, "Wednesday"], [thursday_opens_at, thursday_closes_at, "Thursday"], [friday_opens_at, friday_closes_at, "Friday"], [saturday_opens_at, saturday_closes_at, "Saturday"], [sunday_opens_at, sunday_closes_at, "Sunday"]]

    hours = []

    days.each do |day|
      if day[0] == day[1] || day[0].nil?
        hours << "#{day[2]}: Closed"
      else
        hours << "#{day[2]}: #{day[0].strftime("%l:%M %p")} -#{day[1].strftime("%l:%M %p")}"
      end
    end
    hours.join(", ")
  end

  def postcode_is_formatted
    unless self.latitude.present? && self.longitude.present?
      errors.add(:postcode, "Invalid postcode. Please make sure that the postcode includes a space, eg. 'G2 3AU'.")
    end
  end

  def can_be_published
    # if !self.is_onboarded && self.is_published
    #     errors.add(:name, "The restaurant cannot be published on Vegan Wheels before it is fully onboarded with Stripe.")
    if !self.phone.present? && self.is_published
      errors.add(:phone, "Please add a phone number.")
    elsif !self.about.present? && self.is_published
      errors.add(:about, "Please add a description of the restaurant.")
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @restaurants = Restaurant.includes(:photo_attachment).all.sort_by(&:id)
    @search = params["search"]
    if @search.present?
      @postcode = @search["postcode"]
      @results_array = []

      @results_array << @results = Geocoder.search(@postcode)
      @results_array << @results2 = Geocoder.search(@postcode.split(//).insert(2, " ").join)
      @results_array << @results3 = Geocoder.search(@postcode.split(//).insert(3, " ").join)

      @results_array.each do |result|
        if !result.empty? && result.first.country == "United Kingdom"
          @coordinates = result.first.coordinates
        end
      end

      @restaurants = Restaurant.near(@coordinates, 3.9, units: :km).sort_by(&:id)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @menu_items = @restaurant.menu_items.includes(:section).where(is_active: true)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<div class="container white-content-box">
  <% if user_signed_in? %>
    <div class="row">
      <div id="filter" class="filter__field">
        <%= render "partials/restaurants_index_filter" %>
      </div>
    </div>
  <% end %>
  <% if @search.present? %>
    <div class="row">
      <div class="results-bar">
        <h3 class="results-bar__text">Restaurants near <%= @postcode %></h3>
      </div>
    </div>
  <% end %>
  <div id="user-restaurants">
    <% if Restaurant.where(is_published: true).any? %>
      <%= render "partials/restaurants_index", restaurant: @restaurant %>
    <% else %>
      <h3 class="text-center">Coming soon!</h3>
    <% end %>
  </div>
  <%= render "partials/modal_cart_bg" %>
</div>

app/views/restaurants/index.js.erb
var results = document.getElementById('user-restaurants');
var form = document.getElementById('form')
var filter = document.getElementById('filter')

function filterIndex() {
    if (form) {
        form.remove();
        filter.innerHTML = '<%= j link_to "See all restaurants", restaurants_path, class: "button__fill button__fill--green", remote: true %>';

    } else {
        filter.innerHTML = '<%= j render 'partials/restaurants_index_filter'%>'
    }
    results.innerHTML = '<%= j render "partials/restaurants_index", restaurants: @restaurants %>';
}

filterIndex();

app/views/restaurants/show.html.erb
<div class="container white-content-box">
    <div class="row">
        <div class="col-12 col-lg-5">
            <% if @restaurant.is_currently_closed? %>
                <div class="badge">
                    Closed
                </div>
            <% end %>
            <div class="show-card">
                <div class="show-card__title">
                    <% @restaurant.name.split.each do |word| %>
                        <h1><%= word %></h1>
                    <% end %>
                </div>
                <div class="show-card__image">
                    <% if @restaurant.photo.attached? %>
                        <%= cl_image_tag @restaurant.photo.key, crop: :fill %>
                    <% else %>
                        <%= image_tag "restaurant.jpg" %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-7">
            <div class="info-box">
                <div class="row">
                    <div class="col-12">
                        <h3 class="subtitle">About us</h3>
                        <p> <%= @restaurant.about %> </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <h3 class="subtitle">Contact us</h3>
                        <div class="info-box__section">
                            <div class="info-box__section--box">
                                 <% @restaurant.address.split(",").each do |line| %>
                                    <p><%= line %></p>
                                 <% end %>
                                <%= link_to "See map", "https://www.google.com/maps/search/?api=1&query=#{CGI.escape(@restaurant.address)}", target: "_blank" %>
                                 
                            </div>
                            <div class="info-box__section--box info-box__section--multiple">
                                <div><i class="fas fa-phone-square-alt"></i>
                                <%= @restaurant.phone %></div>
                               <% if @restaurant.website.present? %>
                                <div><i class="fas fa-laptop"></i><%= link_to "Visit our website", @restaurant.website, target: "_blank" %></div>
                                <% end %>
                            </div>
                            <% if @restaurant.email.present? %>
                            <div class="info-box__section--box">
                                <i class="fas fa-envelope-square"></i>
                                <%= @restaurant.email %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="info-box__section">
                            <div class="info-box__section--box">
                                <% if !@restaurant.is_currently_closed? %>
                                    <h3 class="subtitle">Available</h3>
                                <% else %>
                                    <h3 class="subtitle warning">Sorry, we're currently closed. Our typical opening hours are:</h3>
                                <% end %>
                                <%= @restaurant.opening_hours %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% sections = @restaurant.sections.uniq.sort_by { |section| section.order } %>
    <% sections.each do |section| %>
        <div class="row">
            <div class="col-12">
                <div class="section">
                    <h2><%= section.name %></h2>
                </div>
            </div>
        </div>
        <div class="row menu">
            <% @menu_items.each do |item| %>
                <% if item.section == section %>
                <div class="col-12 col-lg-6">
                <%= link_to menu_item_path(item), remote: true do %>
                    <div class="menu__item menu__item--js <%= item.id %>">
                        <div class="menu__item--text">
                            <div class="top">
                                <h3><%= item.name %></h3>
                                <h3 class="price">£
                                <%= to_pounds(item.price) %>
                                </h3>
                            </div>
                            <% if item.description.present? %>
                                <div class="middle">
                                    <p><%= item.description %></p>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
                </div>
                <% end %>
                
            <% end %>
        </div>
    <% end %> 
    <%= render "partials/modal_cart_bg" %>
</div>