config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :rider_users, ActiveAdmin::Devise.config.merge({path: '/rider'})
  ActiveAdmin.routes(self)
  devise_for :users
  resources :dashboard, only: [:index]
  resources :restaurants, only: [ :index, :show]
  root to: 'pages#home'
  get 'error', to: 'pages#error'
  get 'faqs', to: 'pages#faqs'
  get 'terms', to: 'pages#terms'
  get 'privacy', to: 'pages#privacy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create] 
  resources :menu_items, only: [ :show ] do
    resources :order_items, only: [ :create ]
  end
  resources :order_items, only: [ :destroy]
  resources :orders, only: [:index, :create, :destroy] do
    resources :payments, only: :new
    member do
      get 'status'
    end
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  require "sidekiq/web"
  authenticate :admin_user do
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def new
        @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="container white-content-box">
    <div class="row">
        <div class="col-12">
            <div class="checkout mx-auto">
                <h2 class="uppercase font-weight-bold mx-auto">Checkout summary</h1>

                <h3>Your delivery details:</h3>

                <div class="checkout__box">
                    <%= link_to "EDIT", edit_user_registration_path(current_user), class: "checkout__box--link" %>
                    <p><%= current_user.name %></p>
                    <p><%= current_user.address %></p>
                </div>
                
                <% if @order.delivery_instructions.present? %>
                    <h3>Your delivery instructions:</h3>

                    <div class="checkout__box">
                        <p><%= @order.delivery_instructions %></p>
                    </div>
                <% end %>

                <h3>Your order from <%= @order.restaurant.name %>:</h3>

                <div class="checkout__box">
                    <% get_unique(@order.cart).each do |order_item| %>
                    <div class="modal__cart--item" >
                        <% duplicates = get_duplicates(order_item, @order.cart) %>
                        <% if duplicates.empty? %>
                            <div class="modal__cart--itemwrapper">
                                <div>   
                                    <p><%= order_item.quantity %> <%= order_item.menu_item.name %></p>
                                </div>
                            </div>
                            <p>£<%= to_pounds(order_item.total_price) %></p>
                        <% else %>
                            <div class="modal__cart--itemwrapper">
                                <div>
                                    <% quantity_sum = order_item.quantity + duplicates.each_with_object([]) { |oi, array| array << oi.quantity }.sum %>
                                    <% price_sum = order_item.total_price + duplicates.each_with_object([]) { |oi, array| array << oi.total_price }.sum %>
                                    <p><%= quantity_sum %> <%= order_item.menu_item.name %></p>
                                </div>
                            </div>
                            <p>£<%= to_pounds(price_sum) %></p>
                        <% end %>
                    </div>
                    <% if order_item.order_item_options.present? %>
                        <% order_item.order_item_options.each do |option| %>
                        <div class="modal__cart--item">
                            <p class="modal__cart--side"><%= option.menu_option.name %></p>
                            <% if duplicates.empty? %>
                                <% if option.unit_price != 0 %>
                                    <p>£<%= to_pounds(option.total_price) %></p>
                                <% end %>
                            <% else %>
                                <% if option.unit_price != 0 %>
                                    <% count = duplicates.count + 1 %>
                                    <% total = count * option.unit_price %>
                                    <p>£<%= to_pounds(total) %></p>
                                <% end %>
                            <% end %>
                        </div>
                        <% end %>
                    <% end %>
                    <% if order_item.note.present? %>
                        <div class="modal__cart--item">
                            <div class="modal__cart--side">
                                <p>Note: <%= order_item.note %></p>
                            </div>
                        </div>
                    <% end %>
                    <% end %>
                    <div class="modal__cart--item">
                        <p class="font-weight-bold">Subtotal</p>
                        <p id="subtotal">£<%= to_pounds(@order.order_price) %></p>
                    </div>

                    <div class="modal__cart--item">
                        <p>Delivery charge</p>
                        <p>£<%= to_pounds(@order.delivery_price) %></p>
                    </div>

                    <div class="modal__cart--line"></div>
                    <div class="modal__cart--item">
                        <p class="font-weight-bold uppercase">Total</p>
                        <p id="total">£<%= to_pounds(@order.total_price) %></p>
                    </div>
                </div>

                <h3>Delivery estimate: 1 hour</h3>
            
                <div id="pay" class="button__fill button__fill--red">Pay</div>
             
                <%= link_to "Cancel order", order_path(@order), method: :delete, class: "button__fill button__fill--redl" %>  
            </div>
        </div>
    </div>
    <div class="modal-warning modal__bckg">
        <%= render "partials/modal_warning", order: @order %>
    </div>  
</div>
<script src="https://js.stripe.com/v3/"></script>
<script>

    const modalWarning = document.getElementsByClassName('modal-warning')[0];
    const button = document.getElementsByClassName('btn')[0];

    button.addEventListener('click', () => {
        modalWarning.classList.remove('bckg-active')
    })

    const paymentButton = document.getElementById('pay');
    paymentButton.addEventListener('click', () => {
    fetch("<%= status_order_path(@order) %>")
        .then(response => response.json()) 
        .then((data) => {
            const closed = data['restaurant_status']
            const user_too_far = data['user_status']

            if (closed || user_too_far) {
                modalWarning.classList.add('bckg-active')
            } else {
                const stripe = Stripe('<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>', {
                                        stripeAccount: '<%= @order.restaurant.stripe_account_id %>'}
                                );
                stripe.redirectToCheckout({
                    sessionId: '<%= @order.checkout_session_id %>'
                });
            }
        });
    });

</script>